#!/usr/bin/ruby

# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def fib(max)
	a = []
	i = 0
	while true do
		if i == 0 || i == 1
			a[i] = 1
		else
			val = a[i-1] + a[i-2]
			break if val > max
			a[i] = val
		end
		i += 1
	end
	a[1..-1]
end

puts fib(4000000).find_all(&:even?).reduce(0, :+)

# Benchmark:
# 0.000000   0.000000   0.000000 (  0.000104) 
